### ISSUE TITLE
change build flags

### ISSUE THREAD

**Issue by oxcafebabe** [nwjs/nw-gyp#102]
I want to build a npm_module in windows x64 with vs2015, but it fails because of treating warnings as errors when building chromium, plz tell me how to change "-wx" flag to false, thx

**Comment by ghostoy** [comment]
Try https://gyp.gsrc.io/docs/UserDocumentation.md#Exclude-settings-on-a-platform

BTW, nw-gyp is a simple port of node-gyp for NW.js. Please post general questions or bugs to [node-gyp](https://github.com/nodejs/node-gyp/issues).
