### ISSUE TITLE
Invalid path on some pcs for modules with path prepended "\\?\"

### ISSUE THREAD

**Issue by matthewn4444** [nwjs/nw-gyp#104]
Hello,

I have two PCs running Windows 10, one is barebones with no NW js environment and the other (my development machine) has the correct environment. Running the code nw.exe on the barebones PC has an error when loading a module while the development machine does not.

It tries to find the module with a prepended path of **"\\\\?\\"**. So for example, it would try to load the path from **"\\\\?\\C:\path\to\my\app\module.node"**. Which then it would not find the module and just crash.

People who are using my app cannot run it because of the path error. Am I doing something wrong?

My code is [here ](https://github.com/matthewn4444/Lightpack-Filter-and-API/tree/master/nodejs/app-mutex) and [here](https://github.com/matthewn4444/Lightpack-Filter-and-API/tree/master/nodejs/lightpack).

Thanks.

**Comment by ghostoy** [comment]
Does it happen when built with `node-gyp` ? If so, please submit the issue to https://github.com/nodejs/node-gyp. We'll merge the fixes from upstream then.

**Comment by matthewn4444** [comment]
Sorry, I built it incorrectly. I will close this.
