### ISSUE TITLE
the gyp http can't download the header file

### ISSUE THREAD

**Issue by jin-pan** [nwjs/nw-gyp#105]
my configure is fail at download header file.
![aa](https://cloud.githubusercontent.com/assets/17265536/22853516/439f6bd6-f093-11e6-9dc5-add56a6ca20a.JPG)

What can i do at this step?
Did the nw-gyp have proxy setting when use gyp http download?
Please help.
Thank you.

**Comment by jin-pan** [comment]
But i can download this header file by other tool. 
Is it another way to use the header file by hand?

**Comment by jin-pan** [comment]
Ok,The nw-gyp can use proxy.
nw-gyp configure --target=0.14.7 --proxy=http://124.74.274.82:80

**Comment by ghostoy** [comment]
BTW, it uses `http_proxy` and `https_proxy` environments by default.
