### ISSUE TITLE
rebuild serialport on windows for linux platform

### ISSUE THREAD

**Issue by mishkeTz** [nwjs/nw-gyp#113]
Hi,
I am using windows 10, node 8.9.0 and nw 0.25.4. 

I was able to rebuild serialport for win32 and win64 on my windows laptop. But now I want to build it for linux 64 bit (on my windows machine).

I tried it by doing this from inside the serialport folder in node_modules:

`nw-gyp rebuild --runtime=node-webkit --target=0.25.4 --target_arch=x64`

And this is the output when I type nw-gyp list:

> $ nw-gyp list
> gyp info it worked if it ends with ok
> gyp info using nw-gyp@3.6.2
> gyp info using node@8.9.0 | win32 | x64
> 0.25.4
> gyp info ok

I want to rebuild serialport for linux 64 bit, but I am not sure how to do it?

When I build it 

`nwbuild -v 0.25.4 -p linux64 .`

and run it on linux I get the following error:

> serialport.node invalid elf header

**Comment by rogerwang** [comment]
Hello. It's not supported to build linux binaries from Windows system. Close as non-issue. If you have further questions, please post it in our mailing list. Thanks.
https://groups.google.com/forum/#!forum/nwjs-general
