### ISSUE TITLE
Help me. I don't know why I keep hinting at this mistake. 【gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp】

### ISSUE THREAD

**Issue by onburn** [nwjs/nw-gyp#121]
PS F:\work\nw\nwjs-sdk-v0.14.7-win-ia32\BIOIQC\node_modules\sqlite3> nw-gyp rebuild --target=0.14.7 --arch=x64
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@10.8.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\work\\nw\\nwjs-sdk-v0.14.7-win-ia32\\BIOIQC\\node_modules\\sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\lenovo\\.nw-gyp\\0.14.7\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\lenovo\\.nw-gyp\\0.14.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file="C:\\Users\\lenovo\\.nw-gyp\\0.14.7\\<(target_arch)\\node.lib"',
gyp info spawn args   '-Dnw_lib_file="C:\\Users\\lenovo\\.nw-gyp\\0.14.7\\<(target_arch)\\nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=F:\\work\\nw\\nwjs-sdk-v0.14.7-win-ia32\\BIOIQC\\node_modules\\sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\work\\nw\\nwjs-sdk-v0.14.7-win-ia32\\BIOIQC\\node_modules\\sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lenovo\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:359:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.14.7" "--arch=x64"
gyp ERR! cwd F:\work\nw\nwjs-sdk-v0.14.7-win-ia32\BIOIQC\node_modules\sqlite3
gyp ERR! node -v v10.8.0
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok

My development environment：
windows10、nwjs0.14.7sdk、node10.8.0 
I need build plugin sqltie3

Thanks

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
