### ISSUE TITLE
Cannot compile node-sass

### ISSUE THREAD

**Issue by gpetrov** [nwjs/nw-gyp#137]
It is impossible to compile the node-sass for nwjs.

See also https://github.com/sass/node-sass/issues/2759

@rogerwang could you please check?

**Comment by TheJaredWilcurt** [comment]
@gpetrov As long as your globally installed version of Node matches the same version built in to NW.js it will work. `node-sass` downloads files specific to the version of Node installed globally. You can use `nvm`, `nvm-windows` or `nodist`, to change your Node version.

**Comment by gpetrov** [comment]
thanks @TheJaredWilcurt - the node version wasn't the issue. There was just a wrong compiler flag.
Solution is posted in https://github.com/sass/node-sass/issues/2759#issuecomment-612691181

It is a node-sass binding.gyp problem, so this issue can be closed
