### ISSUE TITLE
Using nw-gyp in `npm install` phase

### ISSUE THREAD

**Issue by ghost** [nwjs/nw-gyp#35]
We have some modules that use native module dependencies. How do we build these dependencies for Node-Webkit?

**Comment by maxkorp** [comment]
You can see here how we did it with node-webkit
https://github.com/nodegit/nodegit/blob/master/lifecycleScripts/install.js

(the gist is you have to cd into the module folder and do
```
nw-gyp configure --target={version}
nw-gyp build
```

The above shows how we have our own native module try to detect node-webkit (and atom shell) and build accordingly to prevent the end user from having to do so.

**Comment by ghostoy** [comment]
It's now possible with latest npm. See http://nwjs.io/blog/install-native-modules-with-npm/.
