### ISSUE TITLE
problem with nw-gyp configure

### ISSUE THREAD

**Issue by sat-ish** [nwjs/nw-gyp#36]
Hi,
I am having trouble in nw-gyp configure. First i tried nw-gyp configure in the location (D:\opt\usr). I got the following error
![2err](https://cloud.githubusercontent.com/assets/7879223/3396347/2624e6c0-fd0d-11e3-9d6f-6cd0cac2fb9a.png)
Next i changed the nw-gyp folder to (C:\program files\python27) and tried again...
Now .....
![3err](https://cloud.githubusercontent.com/assets/7879223/3396363/5c503e02-fd0d-11e3-8a0f-4f0ba42dd2d9.png)
Please help...

**Comment by em314159** [comment]
I too have a similiar problem, any suggestions how to fix this
![image](https://cloud.githubusercontent.com/assets/1634248/5950012/99ee1636-a77a-11e4-9c08-99b1d56b7d4a.png)

any suggestions how to fix it ?
