### ISSUE TITLE
error in nw-gyp configure and rebuild --target=0.11.1 or 0.6.3 or 0.8.4 or 0.8.3

### ISSUE THREAD

**Issue by tounsi67** [nwjs/nw-gyp#47]
I cannot download headers when I try to configure my add-on. 

![screenhunter_09 nov 05 14 23](https://cloud.githubusercontent.com/assets/9552805/4918733/e2cbee74-64f3-11e4-9871-1845e38f9ade.jpg)

The build work well when I tape : node-gyp configure build 

Maybe, it's a problem with some version. 

Can anyone give me versions of Node-Webkit, NW-gyp and Node which work? 

Or help me in debugging this matter...

Thanks you in advance for your help.

**Comment by wescopeland** [comment]
@tounsi67 how did you set nw-gyp's proxy parameter?

**Comment by tounsi67** [comment]
I didn't set proxy parameter. 

After a lot of trial, I use a no secure connection to Internet (with my phone...), to download header files for node-webkit.

**Comment by Zenitram-Oriaj** [comment]
how do you set nw-gyp proxy parameter?
