### ISSUE TITLE
how to use nw.exe debug the c++ addon step by step?

### ISSUE THREAD

**Issue by chengzi201412** [nwjs/nw-gyp#53]
I have generate a c++ addon such as "hello.node" by nw-gyp. but there are some Runtime Error in my c++ addon ,and nw.exe just tell me "Uncaught Error: The specified module could not be found." instead of the place of interuption. So i need debug my c++ addon in node-webkit, can you help me ? very thank you!.

**Comment by justinmchase** [comment]
When you compile using nw-gyp be sure to specify the right target, this is working for me:

    nw-gyp --target="0.12.0" configure build
