### ISSUE TITLE
nw-gyp configure on win 7 x64 (Node Serial Port)

### ISSUE THREAD

**Issue by ntha314159** [nwjs/nw-gyp#60]
I get an error when i configure nw-gyp on my win 7 x64 machine. i guess i have python and visual studio is installed.

I am trying to compile the node-serial port for use with node-webkit / nwjs

the target I am using is 0.8.6. Can I use other versions also ?

Here is the error that I get 

![image](https://cloud.githubusercontent.com/assets/1634248/6033413/53e28210-ac3b-11e4-8627-ac960a7d3899.png)

any help would be very much appreciated.

**Comment by jtg-gg** [comment]
add --verbose to debug
in my case it fails to find the python.exe, instead, it found python.bat
the problem solved after i add the path into python.exe in the environment var

**Comment by em314159** [comment]
removing the environment variable PYTHON or setting it to blanks like SET PYTHON= took me one one step ahead.. Thanks @jtg-gg !

Now I am trying to compile node serial port and have this error... any help . Thanks in advance !
![image](https://cloud.githubusercontent.com/assets/1634248/6042077/0a933128-aca8-11e4-81f2-e6fe43c8e493.png)

**Comment by ntha314159** [comment]
Just to update I was able to compile node serialport using node-pre-gyp as detailed in [this issue](https://github.com/voodootikigod/node-serialport/issues/330)
