### ISSUE TITLE
Running App Using nwjs

### ISSUE THREAD

**Issue by abhishekalcanzar** [nwjs/nw-gyp#61]
Hi,

I have created an application that is developed in node js using sails js as framwork. I am able to run that application as an node-webkit application. Now I am trying to create .exe package for installing my application. 

When we run application on server we need to start both of our js file using 
forever start app.js //For API 
forever start master.js //For Master Branch

once forever runs node-webkit can easilty run the application now when I create app.exe of my application then how can we invoke the js file of mine I have referred following tutorials for creating package : https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps

**Comment by justinmchase** [comment]
I'm sorry, this question doesn't seem to make sense. What do you mean when you say "how can we invoke the js file of mine"? Which js file are you referring to? What do you mean by invoke? What does forever have to do with it?

Sorry.

**Comment by ghostoy** [comment]
You've posted on a wrong repo.

If you have any problem using NW.js, please first post your questions to our mailing list https://groups.google.com/forum/#!forum/nwjs-general. If you believe it's a bug or a missing feature, please open an issue on https://github.com/nwjs/nw.js/issues.
