### ISSUE TITLE
creates a not loadable module for node-serialport

### ISSUE THREAD

**Issue by davibe** [nwjs/nw-gyp#7]
I am using nw-gyp on windows with configure --target=0.5.0 to build the module "node-serialport" and use it with node-webkit 0.5.0.

The procedure does work on my mac but since I also need to distribute the application on Windows i have to build it on windows too. My Windows XP virtual machine has Vistual Studio 2010 installed. The build works fine with no errors generating serialport.node but then node-webkit is unable to open serialbox.node to load the module.

Uncaught Error: The specified module could not be found.
C:\Documents and Settings\Administrator\Desktop\baseflight-configurator\win\baseflight-configurator\node_modules\serialport\build\Release\serialport.node 

even if the file is there.

Building with standard node-gyp and loading it with standard node works fine so.. what to do ?

**Comment by fifsky** [comment]
我的天啊，我在这个问题上卡了几个月，今天终于解决了，原来是不能重命名nw.exe文件名称，可是为什么呢，有没有办法可以替换  v0.12.3
