### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dr48** [nwjs/nw-gyp#71]
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, до
бавьте параметр "/m".
C:\Users\Александр\Desktop\NAPP\node_modules\printer\build\node_printer.vcxproj
(44,46): error MSB4025: не удалось загрузить файл проекта. Недопустимый знак дл
я указанной кодировки., строка 44, позиция 46.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Александр\AppData\Roaming\np
m\node_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\Александр\AppData\Roaming\npm\node_modul
es\nw-gyp\bin\nw-gyp.js" "build"
gyp ERR! cwd C:\Users\Александр\Desktop\NAPP\node_modules\printer
gyp ERR! node -v v0.12.5
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

**Comment by ghostoy** [comment]
Please use English to post your issue.

And please try to use latest nw-gyp and NW.js to see if it still happens for you. I will close this issue since it's regarding to a very old version of NW.js.
