### ISSUE TITLE
Error: 404 status code downloading tarball

### ISSUE THREAD

**Issue by maopy208** [nwjs/nw-gyp#74]
gyp http GET http://node-webkit.s3.amazonaws.com/v0.12.7/nw-headers-v0.12.7.tar.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v0.12.7/nw-headers-v0.12.7.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/nw-gyp/lib/install.js:234:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/nw-gyp/node_modules/request/request.js:1008:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "rebuild"
gyp ERR! cwd /Users/Maopy/www/nwtest/node_modules/printer
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok

 i‘ve tried version 0.10.40 0.11.13 0.12.7 & iojs 3.1.0, but the same error

**Comment by godjarl** [comment]
Also get a stuck by this error.

**Comment by pellepelle3** [comment]
set --dist-url=http://dl.nwjs.io
they changed the distro url where things are hosted.

**Comment by ghostoy** [comment]
I'm closing this issue because it's regarding to a very old version of NW.js. Please try with latest releases of nw-gyp and NW.js.
