### ISSUE TITLE
Error: 404 status code downloading 32-bit node.lib

### ISSUE THREAD

**Issue by vkucenko** [nwjs/nw-gyp#75]
I'm trying to rebuild node-sass component 
and all the time getting this error

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\user\Documents\Visual
Studio 2015\Projects\node_modules\gulp-
sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\user\Documents\Visual
Studio 2015\Projects\node_modules
\gulp-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\reque
st.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\user\Documents\Visual
Studio 2015\Projects\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\bin
\node-gyp" "rebuild"
gyp ERR! cwd C:\Users\user\Documents\Visual
Studio 2015\Projects\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
Build failed

**Comment by ankursatriani** [comment]
Hey I am facing the same issue. Did you find any solutions to this?

**Comment by proreact-mj** [comment]
I fixed my similar issue by updating npm
`npm install -g npm`

**Comment by ghostoy** [comment]
I'm closing this issue because it's regarding to a very old version of NW.js. Please try with latest releases of nw-gyp and NW.js.
