### ISSUE TITLE
 'openssl_fips' is not defined

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw-gyp#76]
I'm trying to build greenworks against nw13.0-alpha3, but am hitting an error during the configure stage:

```
 nw-gyp configure --target=0.13.0-alpha3 --arch=ia32

 gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp
```

Does anyone know what the problem is?  

I can't find much info on the 'openssl_fips' error, other than [an issue with node-gyp](https://github.com/nodejs/node-gyp/issues/652).

node v0.12.7
npm v2.11.3
nw-gyp v0.12.4

**Comment by cotejp** [comment]
I'm having the same problem while building serialport. Is anybody still maintaining this project?

**Comment by jetiny** [comment]
me too.

**Comment by gmfc** [comment]
same here, with serialport... @cotejp, any news?

**Comment by djipco** [comment]
The [documentation](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/) for version 0.13 says:  "Starting from 0.13.0, native modules built by node-gyp or npm in upstream can be supported." I guess you could try that? 

As for me, I started using [browser-serialport](https://www.npmjs.com/package/browser-serialport) instead.

Cheers!

**Comment by ghostoy** [comment]
This issue should be fixed with latest nw-gyp and NW.js releases.

**Comment by CharStiles** [comment]
in case it helps anyone else, the problem was resolved for me by restarting the terminal.
