### ISSUE TITLE
Question: Possible to build for windows on linux?

### ISSUE THREAD

**Issue by bgSosh** [nwjs/nw-gyp#77]
I'd love to ditch windows on my development pc, and just use ubuntu for everything.  So I have a (possibly dumb) question:  Is it at all possible to build the .node native extensions for windows, using a linux machine?

Thanks for your help

(Sorry for posting this question in the issues.  I'm just totally fed up with the development experience on windows/node (I'm not blaming nw-gyp!  The fault lies squarely with MS in my opinion).)

**Comment by rurigk** [comment]
Try use wine for windows compilation

**Comment by ghostoy** [comment]
Try wine.

nw-gyp will be simply a port of node-gyp for NW.js. So please report your feature requests to [node-gyp](https://github.com/nodejs/node-gyp/issues).
