### ISSUE TITLE
Unable to build c++ application using nw-gyp build. Error: error MSB6006: “CL.exe” exited with code -1073741515

### ISSUE THREAD

**Issue by kamaldeepoodles** [nwjs/nw-gyp#78]
Please solve this issue related to nw-gyp installation on windows 8.1 described on stackoverflow.

http://stackoverflow.com/questions/33841221/unable-to-build-c-application-using-nw-gyp-build-error-error-msb6006-cl-ex

**Comment by ghostoy** [comment]
This issue should be fixed with latest nw-gyp and NW.js releases.
