### ISSUE TITLE
NW-GYP not recognising Visual Studio 2015 as a valid build tool  on Windows 10 

### ISSUE THREAD

**Issue by jpcharlesworth** [nwjs/nw-gyp#80]
I have been investigating at some length why I cannot build sqlite 3 for Node-Webkit on Windows 10.

I have installed Visual Studio Community Version with C++ but nw-gyp does not recognise GYP_MSVS_VERSION=2015 as referring to a valid version; see attached file MSVSVersionError.txt.
MSVSVersionError.txt

I looked in the code on the nw-gyp repository and it appears that there have been no commits for 2 years, so clearly no changes have been made to accommodate VS2015.
[MSVSVersionError.txt](https://github.com/nwjs/nw-gyp/files/60212/MSVSVersionError.txt)

**Comment by konistehrad** [comment]
:+1: for this. Building against 0.13 betas requires MSVS 2015 compliments V8, but at present nw-gyp doesn't support it. Seeing the same errors.

**Comment by csiqueirasilva** [comment]
There is a [pull request](https://github.com/nwjs/nw-gyp/pull/81) that fix this for non-enterprise editions. I use the 2015 Enterprise Edition and had to add another value in the versions object (in [this file](https://github.com/Rob--/nw-gyp/blob/4f4dcfa53acb6fe6fd255b2cb66b180f3b1677a8/gyp/pylib/gyp/MSVSVersion.py)).

`	  '2015e': VisualStudioVersion('2015',
                                  'Visual Studio 2015',
                                  solution_version='12.00',
                                  project_version='14.0',
                                  flat_sln=False,
                                  uses_vcxproj=True,
                                  path=path,
                                  sdk_based=sdk_based,
                                  default_toolset='v140'),`

Also added this in the version_map:

`	'2015e': ('14.0',),
`

**Comment by ghostoy** [comment]
It should be fixed by our latest release of nw-gyp.
