### ISSUE TITLE
Possible to build on OSX for Windows and Linux

### ISSUE THREAD

**Issue by fredctice** [nwjs/nw-gyp#82]
Hi,

I'm using a MacbookPro with OSX 10.10. I need to create an application (mac, linux, windows) with nw.js and sqlite3.js.
Mac : i rebuild the node's sqlite3 module with nw-gyp to use it with nw.js.

Is it possible to rebuild the module for windows and linux, without installing a virtual machine ?

Thx.

**Comment by ghostoy** [comment]
You can try online CI systems, like Travis CI or AppVeyor.

nw-gyp will be simply a port of node-gyp for NW.js. So please report your feature requests to node-gyp.
