### ISSUE TITLE
nan header errors when building for Node Webkit v0.8.6 using Node v0.10

### ISSUE THREAD

**Issue by jpcharlesworth** [nwjs/nw-gyp#83]
I have been building the node sqlite3 module (from source) for different combinations of versions of Node and Node Webkit

I am running Windows 10 and using Visual Studio Express 2013. In order to get the builds to run I had to work from the developer console of the Visual Studio 2013 Tools

Using Node versions 0.12.9 or 4.2.3, I have been able to build sqlite3 for Node Webkit v0.12.3 with only two warnings and no errors.

However, if I try to build for Node Webkit v0.8.6 using Node versions 0.10.26 or 0.10.41, I always get three compile errors arising from the file nan_implementation_pre_12_inl.h. It appears that the successful builds reported above do not use this header, using nan_implementation_12_inl.h instead.

Since my intention is to migrate from Node Webkit v0.8.6 to v0.12.3 this outcome is satisfactory but, since the 0.8 branch is still maintained, I thought it worth reporting the issue.
Details of the compile errors can be found in the attached file.
nan_errors.txt

I posted this issue on nodejs/nan and received a reply explaining that the build would have been using  Node Webkit versions of the nan headers which differ from the ones on the nan repository. The full nodejs/nan issue is here:
https://github.com/nodejs/nan/issues/525

[nan_errors.txt](https://github.com/nwjs/nw-gyp/files/63862/nan_errors.txt)

**Comment by ghostoy** [comment]
Close this issue since it's regarding to a very old version of nw-gyp and NW.js. Please try with the latest nw-gyp and NW.js.
