### ISSUE TITLE
Do NOT rolling back on ECONNRESET when getting packages

### ISSUE THREAD

**Issue by Allidylls** [nwjs/nw-gyp#87]
C:\Users\lenovo\Programs\nw.js\node_modules\serialport>nw-gyp rebuild --target=0.13.0-rc2
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.4.0 | win32 | ia32
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/node.lib
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/x64/node.lib
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw.lib
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/x64/nw.lib
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw.lib
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/x64/nw.lib
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/node.lib
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/x64/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TCP.onread (net.js:550:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\lenovo\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" "rebuild" "--target=0.13.0-rc2"
gyp ERR! cwd C:\Users\lenovo\Programs\nw.js\node_modules\serialport
gyp ERR! node -v v4.4.0
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok

C:\Users\lenovo\Programs\nw.js\node_modules\serialport>nw-gyp rebuild --target=0.13.0-rc2
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.4.0 | win32 | ia32
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz
gyp WARN install got an error, rolling back install
^CTerminate batch job (Y/N)? y

C:\Users\lenovo\Programs\nw.js\node_modules\serialport>nw-gyp rebuild --target=0.13.0-rc2
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.4.0 | win32 | ia32
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz
gyp http 200 http://node-webkit.s3.amazonaws.com/v0.13.0-rc2/nw-headers-v0.13.0-rc2.tar.gz

**Comment by fanchou** [comment]
it's too slow!  Can we change the URL?

**Comment by ghostoy** [comment]
@fanchou You can try with `--disturl=https://dl.nwjs.io`. That may be a little bit faster.

**Comment by ghostoy** [comment]
nw-gyp is simply a port of node-gyp. If you are requesting new features, please post your issue on [node-gyp](https://github.com/nodejs/node-gyp/issues).
